project:
  type: website
  output-dir: gh-pages

website:
  title: "Outreach"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  site-url: https://aieoutreach.github.io/presentation/
  google-analytics: G-YZFTXBJG2M
  twitter-card: true
  open-graph: true

format:
  html:
    theme: spacelab
    css: styles.css



